---
title: "数据可视化作业"
author: "2021103789 吴心怡"
date: "2021/12/27"
output:
  prettydoc::html_pretty:
    theme: architect
    highlight: github
# vignette: >
#   %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
```

# 读入数据

```{r}
rm(list=ls())  #清除环境变量
options(warn=-1)  #不显示warning信息
library(ggplot2)
library(ggridges)
mydata<-read.csv("D:/统计学院 研究生 文件/课程/数据可视化/HW2/data_scaling2.csv",header=T, sep=',')
```

```{r}
mydata
```

# 绘制图像

```{r}

dd1<-data.frame(影片名称=mydata$影片名称,上映年份=mydata$上映年份,差距=mydata$gap,类别=mydata$类别,制作成本=mydata$制作成本.亿元.)
```



```{r}
#初步画图
ggplot(dd1, aes(x=差距, y=上映年份))+
  geom_point()
```

```{r}
#加入类别元素
ggplot(dd1, aes(x=差距, y=上映年份,color=类别))+
  geom_point()
```

```{r}
#加入制作成本作为大小元素
ggplot(dd1, aes(x=差距, y=上映年份,color=类别))+
  geom_point(aes(size=制作成本))
```

```{r}
#改变y轴显示
ggplot(dd1, aes(x=差距, y=上映年份,color=类别))+
  geom_point(aes(size=制作成本))+
  scale_y_continuous(breaks=seq(2014, 2021, 1))  

```

```{r}
#去掉背景网格线
ggplot(dd1, aes(x=差距, y=上映年份,color=类别))+
  geom_point(aes(size=制作成本))+
  scale_y_continuous(breaks=seq(2014, 2021, 1))+
  theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank())

```

```{r}
#加入y轴网格线，并置于底层
ggplot(dd1, aes(x=差距, y=上映年份,color=类别))+
  geom_hline(yintercept = seq(2014, 2021, 1),color = 'white')+
  geom_point(aes(size=制作成本))+
  scale_y_continuous(breaks=seq(2014, 2021, 1))+
  theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank())
```

```{r}
#增加图表标题，并居中
ggplot(dd1, aes(x=差距, y=上映年份,color=类别))+
  geom_hline(yintercept = seq(2014, 2021, 1),color = 'white')+
  geom_point(aes(size=制作成本))+
  scale_y_continuous(breaks=seq(2014, 2021, 1))+
  theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank())+
  labs(title="豆瓣评分和电影票房的差距")+
  theme(plot.title = element_text(hjust=0.5))
  
```






